language: java
jdk:
  - openjdk8
branches:
  only:
    - master
#Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - ds257873@naver.com